In [2]:
import csv
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.mixture import GaussianMixture
from collections import defaultdict
import pandas as pd
from IPython.display import JSON
from matplotlib import colors

## Data Input

In [7]:
chromosome_rohs = {
    "X": defaultdict(list)
}
for i in range(1, 24):
    chromosome_rohs[str(i)] = defaultdict(list)

with open(os.path.abspath("ROH Data/1500kb - Minimum 100 SNPs.csv"), "r") as file_handle:
    header = None
    reader = csv.reader(file_handle)
    for row in reader:
        if not header:
            header = [f"{i}. {name}" for i, name in enumerate(row)] # Add numerical indices to account for repeating headers
            continue
        for index, item in enumerate(row):
            try:
                item = float(item)
            except ValueError:
                item = str(item)
            chromosome_rohs[row[int(header.index("1. Chromosome Name"))]][header[index]].append(item)
for rohs in chromosome_rohs.values():
    rohs = dict(rohs)
    display(pd.DataFrame(rohs))

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0030,X,125314410.0,127060007.0,1745597.0,438710.0,438821.0,SNP_A-2250799,SNP_A-4198131,112.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0109,X,74293145.0,76316120.0,2022975.0,435672.0,435793.0,SNP_A-2270068,SNP_A-4274411,122.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0142,X,84296239.0,87570286.0,3274047.0,436143.0,436415.0,SNP_A-2233417,SNP_A-1794859,273.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0260,X,14269493.0,16540532.0,2271039.0,432413.0,432574.0,SNP_A-1998270,SNP_A-1998297,162.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0260,X,23601896.0,25226563.0,1624667.0,433081.0,433215.0,SNP_A-2312294,SNP_A-2060726,135.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,ML2027,X,111740955.0,113366777.0,1625822.0,437659.0,437774.0,SNP_A-1927833,SNP_A-1832539,116.0,...,Tanzania,Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
75,ML2102,X,74293145.0,76236538.0,1943393.0,435672.0,435792.0,SNP_A-2270068,SNP_A-2129463,121.0,...,"Kitui, Kenya",Kenya,1968.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
76,ML2144,X,74198643.0,76236538.0,2037895.0,435669.0,435792.0,SNP_A-2167000,SNP_A-2129463,124.0,...,"MURANG'A, Kenya",Kenya,1972.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
77,ML2244,X,74583803.0,76316120.0,1732317.0,435689.0,435793.0,SNP_A-2305849,SNP_A-4274411,105.0,...,"KISUMU, Kenya",Kenya,1966.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
78,ML2272,X,74495461.0,76236538.0,1741077.0,435679.0,435792.0,SNP_A-2245615,SNP_A-2129463,114.0,...,"Thika, Kenya",Kenya,1978.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0057,1.0,41595340.0,43558355.0,1963015.0,6210.0,6522.0,SNP_A-1856188,SNP_A-1916202,313.0,...,Tanzania,Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0057,1.0,48427801.0,51249676.0,2821875.0,7166.0,7453.0,SNP_A-1951535,SNP_A-1917826,288.0,...,Tanzania,Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0079,1.0,71866223.0,73734573.0,1868350.0,11204.0,11443.0,SNP_A-2172025,SNP_A-2287814,240.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0103,1.0,218067189.0,219659841.0,1592652.0,30923.0,31180.0,SNP_A-2160379,SNP_A-1851714,258.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0137,1.0,118430648.0,120325425.0,1894777.0,18682.0,18987.0,SNP_A-4303769,SNP_A-4237592,306.0,...,Tanzania,Tanzania,1947.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,ML2263,1.0,168595183.0,173868337.0,5273154.0,22803.0,23610.0,SNP_A-1957718,SNP_A-2139301,808.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
139,ML2263,1.0,174071054.0,175891995.0,1820941.0,23667.0,23955.0,SNP_A-1808371,SNP_A-2037438,289.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
140,ML2263,1.0,179791462.0,181679613.0,1888151.0,24555.0,24930.0,SNP_A-1832623,SNP_A-4228403,376.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
141,ML2278,1.0,177857689.0,179444477.0,1586788.0,24227.0,24473.0,SNP_A-1783280,SNP_A-4263785,247.0,...,"KAGERA, Tanzania",Tanzania,1980.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
142,ML2285,1.0,184415137.0,188106976.0,3691839.0,25346.0,25875.0,SNP_A-4236699,SNP_A-4152964,530.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0005,2.0,98926671.0,101182357.0,2255686.0,51220.0,51603.0,SNP_A-2215723,SNP_A-2291102,384.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0005,2.0,103294246.0,105320341.0,2026095.0,51980.0,52240.0,SNP_A-2060558,SNP_A-4232453,261.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0005,2.0,193473143.0,195567450.0,2094307.0,64912.0,65092.0,SNP_A-4223737,SNP_A-2118329,181.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0016,2.0,53473610.0,55794944.0,2321334.0,45690.0,46099.0,SNP_A-2030184,SNP_A-4292816,410.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0016,2.0,71598139.0,73245577.0,1647438.0,48624.0,48779.0,SNP_A-1935891,SNP_A-4255246,156.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,ML2257,2.0,145333622.0,147096674.0,1763052.0,58180.0,58366.0,SNP_A-4259496,SNP_A-2057687,187.0,...,"Siaya, Kenya",Kenya,1974.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
176,ML2257,2.0,224915228.0,227207003.0,2291775.0,69665.0,70088.0,SNP_A-2262593,SNP_A-2114100,424.0,...,"Siaya, Kenya",Kenya,1974.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
177,ML2266,2.0,177643617.0,179211456.0,1567839.0,62744.0,63024.0,SNP_A-2090355,SNP_A-2065895,281.0,...,"MURANG'A, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
178,ML2267,2.0,193449506.0,195208096.0,1758590.0,64909.0,65049.0,SNP_A-2206658,SNP_A-1841064,141.0,...,"MURANG'A, Kenya",Kenya,1978.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
179,ML2287,2.0,135461599.0,137149683.0,1688084.0,56689.0,56885.0,SNP_A-1828766,SNP_A-1876552,197.0,...,"MURANG'A, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0016,3.0,141984880.0,144136370.0,2151490.0,94391.0,94637.0,SNP_A-1848290,SNP_A-2241781,247.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0030,3.0,173887236.0,175740008.0,1852772.0,98826.0,99117.0,SNP_A-2075581,SNP_A-4302503,292.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0059,3.0,20047391.0,22509342.0,2461951.0,76496.0,76999.0,SNP_A-4248694,SNP_A-1879290,504.0,...,"Bukoba, Tanzania",Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0157,3.0,88624272.0,90346746.0,1722474.0,87381.0,87531.0,SNP_A-2190308,SNP_A-2213614,151.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0170,3.0,63638255.0,65515311.0,1877056.0,83582.0,84027.0,SNP_A-2053910,SNP_A-2038233,446.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,ML2218,3.0,16918882.0,18550975.0,1632093.0,76165.0,76330.0,SNP_A-2061261,SNP_A-1971913,166.0,...,"Kiambu, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
108,ML2229,3.0,165103612.0,166555700.0,1452088.0,97698.0,97860.0,SNP_A-1809534,SNP_A-4258840,163.0,...,"NYAMIRA, Kenya",Kenya,?,unknown,unknown,"Bantus, all included","Bantus, all included","Kenyan, all included","Kenyan, all included","Kenyan, all included"
109,ML2239,3.0,85722145.0,88116629.0,2394484.0,87032.0,87323.0,SNP_A-2057068,SNP_A-1915149,292.0,...,"MARAGWA, Kenya",Kenya,1973.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
110,ML2259,3.0,99922327.0,102199107.0,2276780.0,88049.0,88395.0,SNP_A-2094474,SNP_A-2008920,347.0,...,"Kiambu, Kenya",Kenya,1979.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
111,ML2278,3.0,157825246.0,160685328.0,2860082.0,96614.0,97070.0,SNP_A-4234449,SNP_A-2144020,457.0,...,"KAGERA, Tanzania",Tanzania,1980.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0005,4.0,96601368.0,100455785.0,3854417.0,117170.0,117646.0,SNP_A-2090003,SNP_A-1842764,477.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0005,4.0,157661232.0,159278662.0,1617430.0,125523.0,125750.0,SNP_A-2239469,SNP_A-4199515,228.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0030,4.0,187639354.0,191014755.0,3375401.0,130299.0,130758.0,SNP_A-2190434,SNP_A-4235158,460.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0057,4.0,115506780.0,117251979.0,1745199.0,119826.0,120020.0,SNP_A-2198210,SNP_A-2258984,195.0,...,Tanzania,Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0057,4.0,137731126.0,139799629.0,2068503.0,122588.0,122950.0,SNP_A-4237259,SNP_A-4244002,363.0,...,Tanzania,Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,ML2229,4.0,72910046.0,74567884.0,1657838.0,113525.0,113749.0,SNP_A-1780334,SNP_A-1977584,225.0,...,"NYAMIRA, Kenya",Kenya,?,unknown,unknown,"Bantus, all included","Bantus, all included","Kenyan, all included","Kenyan, all included","Kenyan, all included"
122,ML2229,4.0,106474561.0,112639758.0,6165197.0,118460.0,119336.0,SNP_A-1950018,SNP_A-2130773,877.0,...,"NYAMIRA, Kenya",Kenya,?,unknown,unknown,"Bantus, all included","Bantus, all included","Kenyan, all included","Kenyan, all included","Kenyan, all included"
123,ML2263,4.0,9819488.0,12647728.0,2828240.0,103894.0,104566.0,SNP_A-2112723,SNP_A-2160593,673.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
124,ML2263,4.0,12653516.0,14878277.0,2224761.0,104568.0,105069.0,SNP_A-2179225,SNP_A-4272733,502.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
125,ML2264,4.0,159596452.0,161315920.0,1719468.0,125791.0,126025.0,SNP_A-2104066,SNP_A-1885550,235.0,...,"Thika, Kenya",Kenya,1974.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0005,5.0,43021127.0,44516774.0,1495647.0,138227.0,138356.0,SNP_A-4293134,SNP_A-4210938,130.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0005,5.0,58764278.0,62592250.0,3827972.0,140017.0,140590.0,SNP_A-1959476,SNP_A-4247410,574.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0005,5.0,89047168.0,90667140.0,1619972.0,144262.0,144463.0,SNP_A-4222869,SNP_A-2235500,202.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0030,5.0,129725283.0,131355797.0,1630514.0,150316.0,150453.0,SNP_A-2283425,SNP_A-4206095,138.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0041,5.0,81089201.0,82654559.0,1565358.0,143295.0,143555.0,SNP_A-2011006,SNP_A-1854329,261.0,...,Uganda,Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,ML2178,5.0,63188539.0,64735458.0,1546919.0,140684.0,140890.0,SNP_A-2254990,SNP_A-2211412,207.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
152,ML2185,5.0,56757293.0,58325091.0,1567798.0,139578.0,139914.0,SNP_A-4239306,SNP_A-4225337,337.0,...,"MURANG'A, Kenya",Kenya,1968.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
153,ML2244,5.0,52228994.0,54277851.0,2048857.0,138739.0,139151.0,SNP_A-1826562,SNP_A-2296229,413.0,...,"KISUMU, Kenya",Kenya,1966.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
154,ML2249,5.0,42878860.0,44516774.0,1637914.0,138198.0,138356.0,SNP_A-2121851,SNP_A-4210938,159.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
155,ML2278,5.0,42655073.0,44308122.0,1653049.0,138177.0,138334.0,SNP_A-2261841,SNP_A-1846134,158.0,...,"KAGERA, Tanzania",Tanzania,1980.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0002,6.0,17375587.0,18880846.0,1505259.0,162846.0,163110.0,SNP_A-2083539,SNP_A-4283558,265.0,...,Tanzania,Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0002,6.0,90853821.0,93840506.0,2986685.0,174113.0,174613.0,SNP_A-4221708,SNP_A-2156112,501.0,...,Tanzania,Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0002,6.0,96560287.0,98242896.0,1682609.0,174946.0,175187.0,SNP_A-1793967,SNP_A-1959629,242.0,...,Tanzania,Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0005,6.0,100254047.0,102399882.0,2145835.0,175506.0,175803.0,SNP_A-1862596,SNP_A-4231373,298.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0058,6.0,29510666.0,31088582.0,1577916.0,164867.0,165316.0,SNP_A-1784543,SNP_A-4281818,450.0,...,"Bukoba, Tanzania",Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,ML2028,6.0,145522349.0,147647700.0,2125351.0,182266.0,182528.0,SNP_A-2072582,SNP_A-1988021,263.0,...,"Bukoba, Tanzania",Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
86,ML2049,6.0,35031842.0,36638581.0,1606739.0,166050.0,166227.0,SNP_A-2310384,SNP_A-2161847,178.0,...,"MURANG'A, Kenya",Kenya,1968.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
87,ML2139,6.0,120034143.0,122007860.0,1973717.0,178368.0,178633.0,SNP_A-2084615,SNP_A-4218420,266.0,...,"Bukoba, Tanzania",Tanzania,1979.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
88,ML2178,6.0,47559842.0,49131172.0,1571330.0,168143.0,168399.0,SNP_A-1985936,SNP_A-1867376,257.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
89,ML2285,6.0,80532039.0,82672802.0,2140763.0,172501.0,172868.0,SNP_A-2150789,SNP_A-1910502,368.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0024,7.0,88235079.0,90511244.0,2276165.0,200012.0,200384.0,SNP_A-1876672,SNP_A-2048464,373.0,...,"Mbale, Uganda",Uganda,1969.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0058,7.0,82682474.0,89950482.0,7268008.0,199278.0,200297.0,SNP_A-1807934,SNP_A-2217269,1020.0,...,"Bukoba, Tanzania",Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0086,7.0,113134647.0,114648083.0,1513436.0,203160.0,203278.0,SNP_A-4253824,SNP_A-1834039,119.0,...,Tanzania,Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0142,7.0,77918484.0,80300775.0,2382291.0,198508.0,198910.0,SNP_A-1990245,SNP_A-2296017,403.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0163,7.0,47308808.0,49294428.0,1985620.0,195262.0,195627.0,SNP_A-2121718,SNP_A-2042398,366.0,...,Uganda,Uganda,1951.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,ML2197,7.0,79266999.0,81259692.0,1992693.0,198752.0,199048.0,SNP_A-2295104,SNP_A-1990336,297.0,...,"Kitui, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
85,ML2197,7.0,125464161.0,127558837.0,2094676.0,204588.0,204926.0,SNP_A-4196725,SNP_A-4217775,339.0,...,"Kitui, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
86,ML2237,7.0,47677313.0,49506854.0,1829541.0,195332.0,195657.0,SNP_A-2098068,SNP_A-2224257,326.0,...,"Nyeri, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
87,ML2245,7.0,116107162.0,120197437.0,4090275.0,203432.0,203849.0,SNP_A-2060488,SNP_A-4266562,418.0,...,"MARAGWA, Kenya",Kenya,1977.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
88,ML2278,7.0,147685755.0,149264479.0,1578724.0,207982.0,208156.0,SNP_A-2153747,SNP_A-1932445,175.0,...,"KAGERA, Tanzania",Tanzania,1980.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0079,8.0,92023630.0,93656356.0,1632726.0,224780.0,224933.0,SNP_A-1994233,SNP_A-2309006,154.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0115,8.0,62133694.0,64008938.0,1875244.0,220687.0,221033.0,SNP_A-1993501,SNP_A-1879518,347.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0199,8.0,49769053.0,52585658.0,2816605.0,218645.0,219084.0,SNP_A-1941416,SNP_A-1993247,440.0,...,"BUSOGA, Uganda",Uganda,1963.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0260,8.0,229189.0,2152119.0,1922930.0,209514.0,209884.0,SNP_A-4266708,SNP_A-4266719,371.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0315,8.0,87026041.0,89680001.0,2653960.0,224090.0,224455.0,SNP_A-1812906,SNP_A-4282368,366.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,ML2178,8.0,40825954.0,42737547.0,1911593.0,218191.0,218417.0,SNP_A-1914463,SNP_A-4206612,227.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
71,ML2178,8.0,83457336.0,86064692.0,2607356.0,223715.0,224036.0,SNP_A-1994049,SNP_A-4302295,322.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
72,ML2203,8.0,79821461.0,81486691.0,1665230.0,223258.0,223491.0,SNP_A-2196294,SNP_A-2073856,234.0,...,"Thika, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
73,ML2204,8.0,50270735.0,52695154.0,2424419.0,218716.0,219105.0,SNP_A-1954990,SNP_A-4250483,390.0,...,"MURANG'A, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
74,ML2263,8.0,49713697.0,51367828.0,1654131.0,218629.0,218898.0,SNP_A-1960569,SNP_A-2075880,270.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0013,9.0,33435895.0,35815413.0,2379518.0,241212.0,241489.0,SNP_A-1901021,SNP_A-1790752,278.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0013,9.0,101027581.0,102528615.0,1501034.0,247322.0,247492.0,SNP_A-1884007,SNP_A-4267611,171.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0030,9.0,9904448.0,12273944.0,2369496.0,236486.0,236955.0,SNP_A-2073325,SNP_A-2243057,470.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0288,9.0,106863085.0,108852047.0,1988962.0,248328.0,248639.0,SNP_A-2245141,SNP_A-2207457,312.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0330,9.0,126259954.0,132099642.0,5839688.0,252232.0,252919.0,SNP_A-1894165,SNP_A-1888329,688.0,...,"CHAHAFI, Uganda",Uganda,1951.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0389,9.0,136560342.0,138260649.0,1700307.0,253471.0,253703.0,SNP_A-2102155,SNP_A-4240188,233.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0412,9.0,25747569.0,27959440.0,2211871.0,239681.0,240173.0,SNP_A-1954041,SNP_A-4226215,493.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML0435,9.0,83580964.0,86273243.0,2692279.0,244392.0,244801.0,SNP_A-2312157,SNP_A-1797869,410.0,...,"Bukoba, Tanzania",Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML0435,9.0,93158079.0,94714434.0,1556355.0,246115.0,246334.0,SNP_A-4240809,SNP_A-2205651,220.0,...,"Bukoba, Tanzania",Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML0589,9.0,32578258.0,35642384.0,3064126.0,241022.0,241464.0,SNP_A-1939965,SNP_A-1801196,443.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML0602,9.0,31371316.0,32900292.0,1528976.0,240802.0,241119.0,SNP_A-1921925,SNP_A-2245986,318.0,...,"Bukoba, Tanzania",Tanzania,1953.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
11,ML0768,9.0,126229736.0,128913453.0,2683717.0,252229.0,252587.0,SNP_A-1831563,SNP_A-2254392,359.0,...,"Machakos, Kenya",Kenya,1955.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
12,ML0768,9.0,128926726.0,132099642.0,3172916.0,252589.0,252919.0,SNP_A-4250780,SNP_A-1888329,331.0,...,"Machakos, Kenya",Kenya,1955.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
13,ML0915,9.0,124375437.0,125884677.0,1509240.0,251994.0,252181.0,SNP_A-2251509,SNP_A-1956201,188.0,...,"BUNGOMA, Kenya",Kenya,1956.0,"Uganda, Bantus","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
14,ML0959,9.0,80958355.0,82986774.0,2028419.0,243899.0,244300.0,SNP_A-1926871,SNP_A-4213525,402.0,...,"MURANG'A, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
15,ML1000,9.0,101027581.0,103258996.0,2231415.0,247322.0,247630.0,SNP_A-1884007,SNP_A-4213580,309.0,...,"Bukoba, Tanzania",Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
16,ML1005,9.0,70234710.0,72601982.0,2367272.0,242007.0,242496.0,SNP_A-1914371,SNP_A-2272338,490.0,...,Tanzania,Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
17,ML1008,9.0,86763829.0,88444339.0,1680510.0,244898.0,245160.0,SNP_A-1831451,SNP_A-2190577,263.0,...,"Bukoba, Tanzania",Tanzania,1966.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
18,ML1130,9.0,105499015.0,107473610.0,1974595.0,248019.0,248423.0,SNP_A-1780713,SNP_A-2058078,405.0,...,Tanzania,Tanzania,1966.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
19,ML1295,9.0,32900292.0,35126146.0,2225854.0,241119.0,241412.0,SNP_A-2245986,SNP_A-2139577,294.0,...,"Bukoba, Tanzania",Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
20,ML1336,9.0,92319936.0,94899560.0,2579624.0,245929.0,246350.0,SNP_A-1997190,SNP_A-4292304,422.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
21,ML1376,9.0,101311483.0,102878308.0,1566825.0,247373.0,247554.0,SNP_A-1997364,SNP_A-2138980,182.0,...,"Kericho, Kenya",Kenya,1967.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
22,ML1394,9.0,104056438.0,106401531.0,2345093.0,247773.0,248208.0,SNP_A-2109677,SNP_A-1957211,436.0,...,"Machakos, Kenya",Kenya,1961.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
23,ML1401,9.0,16208659.0,18066712.0,1858053.0,237819.0,238275.0,SNP_A-2054147,SNP_A-4281697,457.0,...,"Embu, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
24,ML1401,9.0,27944222.0,32554173.0,4609951.0,240170.0,241021.0,SNP_A-1945080,SNP_A-1996549,852.0,...,"Embu, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML1425,9.0,93834123.0,95445685.0,1611562.0,246243.0,246431.0,SNP_A-1828219,SNP_A-4237621,189.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
26,ML1478,9.0,93832040.0,96048845.0,2216805.0,246241.0,246504.0,SNP_A-2038113,SNP_A-2314414,264.0,...,"Machakos, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
27,ML1530,9.0,34881317.0,36717599.0,1836282.0,241380.0,241619.0,SNP_A-1903589,SNP_A-2192162,240.0,...,"Kakamega, Kenya",Kenya,1963.0,"Abaluhya, Kenya, close to Bantus","Abaluhya, Kenya, close to Bantus","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
28,ML1667,9.0,33547023.0,36529122.0,2982099.0,241221.0,241598.0,SNP_A-2118209,SNP_A-4248275,378.0,...,"Kisii, Kenya",Kenya,1961.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
29,ML1668,9.0,33911977.0,36529122.0,2617145.0,241275.0,241598.0,SNP_A-2305856,SNP_A-4248275,324.0,...,"Kisii, Kenya",Kenya,1961.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
30,ML1693,9.0,100873673.0,103258996.0,2385323.0,247302.0,247630.0,SNP_A-1841295,SNP_A-4213580,329.0,...,"Embu, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
31,ML1725,9.0,33593565.0,35466356.0,1872791.0,241224.0,241447.0,SNP_A-4245216,SNP_A-1889825,224.0,...,"Laikipia, Kenya",Kenya,1966.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
32,ML1766,9.0,116495996.0,118185562.0,1689566.0,250308.0,250653.0,SNP_A-2179948,SNP_A-2231142,346.0,...,"Kitui, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
33,ML1776,9.0,30013139.0,32700249.0,2687110.0,240580.0,241048.0,SNP_A-2133015,SNP_A-1871037,469.0,...,"Bukoba, Tanzania",Tanzania,1975.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
34,ML1788,9.0,25554892.0,27177216.0,1622324.0,239651.0,239954.0,SNP_A-1996311,SNP_A-2095892,304.0,...,"RUIRU, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
35,ML1800,9.0,126261026.0,127772096.0,1511070.0,252233.0,252397.0,SNP_A-1997976,SNP_A-2244452,165.0,...,"Nyeri, Kenya",Kenya,1974.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
36,ML1815,9.0,93307442.0,96096004.0,2788562.0,246144.0,246512.0,SNP_A-1896448,SNP_A-2109531,369.0,...,"Thika, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
37,ML1815,9.0,96292326.0,99714386.0,3422060.0,246521.0,247037.0,SNP_A-4283029,SNP_A-1831493,517.0,...,"Thika, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
38,ML1815,9.0,99747076.0,104395399.0,4648323.0,247039.0,247822.0,SNP_A-2276822,SNP_A-1997426,784.0,...,"Thika, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
39,ML1815,9.0,105144699.0,107022613.0,1877914.0,247972.0,248355.0,SNP_A-1856155,SNP_A-2278601,384.0,...,"Thika, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
40,ML1863,9.0,18652292.0,20183051.0,1530759.0,238417.0,238739.0,SNP_A-1996124,SNP_A-4204174,323.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
41,ML1870,9.0,122060527.0,124032645.0,1972118.0,251630.0,251923.0,SNP_A-2166313,SNP_A-2054253,294.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
42,ML1871,9.0,106502249.0,108685808.0,2183559.0,248231.0,248616.0,SNP_A-2282300,SNP_A-2034617,386.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
43,ML1944,9.0,81209418.0,83086772.0,1877354.0,243948.0,244314.0,SNP_A-2167327,SNP_A-2029702,367.0,...,"Thika, Kenya",Kenya,1977.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
44,ML2029,9.0,20115259.0,22194445.0,2079186.0,238721.0,239125.0,SNP_A-1847300,SNP_A-2123493,405.0,...,"Bukoba, Tanzania",Tanzania,1975.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
45,ML2142,9.0,71877971.0,73437990.0,1560019.0,242348.0,242670.0,SNP_A-1808097,SNP_A-4256763,323.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
46,ML2142,9.0,73452020.0,75019873.0,1567853.0,242674.0,242929.0,SNP_A-2241173,SNP_A-2139988,256.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
47,ML2142,9.0,75044637.0,76615277.0,1570640.0,242931.0,243155.0,SNP_A-2126617,SNP_A-4229337,225.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
48,ML2196,9.0,126417601.0,128726795.0,2309194.0,252245.0,252555.0,SNP_A-2228976,SNP_A-2128146,311.0,...,"Nyeri, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0016,10.0,82705777.0,84384925.0,1679148.0,268835.0,269121.0,SNP_A-2270506,SNP_A-2082115,287.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0024,10.0,121281931.0,122818836.0,1536905.0,275785.0,276167.0,SNP_A-2193224,SNP_A-1907023,383.0,...,"Mbale, Uganda",Uganda,1969.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0041,10.0,101924926.0,103478114.0,1553188.0,272194.0,272380.0,SNP_A-2294258,SNP_A-4272514,187.0,...,Uganda,Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0041,10.0,103581467.0,106871459.0,3289992.0,272382.0,272916.0,SNP_A-2214060,SNP_A-2242686,535.0,...,Uganda,Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0041,10.0,106876621.0,111323629.0,4447008.0,272918.0,273869.0,SNP_A-4250280,SNP_A-4231236,952.0,...,Uganda,Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,ML2142,10.0,95162721.0,97167744.0,2005023.0,271069.0,271375.0,SNP_A-1905224,SNP_A-2004168,307.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
70,ML2142,10.0,97266482.0,100089641.0,2823159.0,271391.0,271860.0,SNP_A-1885532,SNP_A-1905823,470.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
71,ML2147,10.0,110389386.0,112602292.0,2212906.0,273720.0,274091.0,SNP_A-2048123,SNP_A-2259821,372.0,...,"Machakos, Kenya",Kenya,1961.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
72,ML2218,10.0,68626505.0,70602984.0,1976479.0,266544.0,266774.0,SNP_A-1833445,SNP_A-4195330,231.0,...,"Kiambu, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
73,ML2244,10.0,95465326.0,97244295.0,1778969.0,271147.0,271389.0,SNP_A-2298862,SNP_A-2082608,243.0,...,"KISUMU, Kenya",Kenya,1966.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0030,11.0,89603003.0,91263109.0,1660106.0,292951.0,293273.0,SNP_A-2277353,SNP_A-4199669,323.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0141,11.0,23958779.0,26002063.0,2043284.0,283566.0,283961.0,SNP_A-4249496,SNP_A-2281863,396.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0320,11.0,48956881.0,50567700.0,1610819.0,287897.0,287998.0,SNP_A-4250756,SNP_A-2257206,102.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0321,11.0,42174140.0,44887617.0,2713477.0,286902.0,287462.0,SNP_A-2249979,SNP_A-4299979,561.0,...,Tanzania,Tanzania,1948.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0385,11.0,56314955.0,58200377.0,1885422.0,288271.0,288586.0,SNP_A-1911612,SNP_A-4299966,316.0,...,"Kiambu, Kenya",Kenya,1955.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ML2248,11.0,46218598.0,48586010.0,2367412.0,287681.0,287883.0,SNP_A-1868369,SNP_A-2219688,203.0,...,"MURANG'A, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
96,ML2269,11.0,9419893.0,10963979.0,1544086.0,280383.0,280662.0,SNP_A-1828361,SNP_A-2128356,280.0,...,"NANYUKI, Kenya",Kenya,1973.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
97,ML2269,11.0,12978400.0,15364027.0,2385627.0,281236.0,281696.0,SNP_A-2230891,SNP_A-4230518,461.0,...,"NANYUKI, Kenya",Kenya,1973.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
98,ML2280,11.0,30578557.0,32086467.0,1507910.0,284723.0,284950.0,SNP_A-2210178,SNP_A-2009533,228.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
99,ML2280,11.0,110864544.0,113059344.0,2194800.0,296957.0,297355.0,SNP_A-2060663,SNP_A-2062296,399.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0005,12.0,52574919.0,54364456.0,1789537.0,310406.0,310661.0,SNP_A-1879069,SNP_A-1951489,256.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0016,12.0,26091832.0,28670357.0,2578525.0,306294.0,306797.0,SNP_A-2205472,SNP_A-1801051,504.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0016,12.0,29627037.0,31700072.0,2073035.0,307017.0,307499.0,SNP_A-4218224,SNP_A-2086982,483.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0058,12.0,58460145.0,60694975.0,2234830.0,311227.0,311522.0,SNP_A-4219908,SNP_A-1838243,296.0,...,"Bukoba, Tanzania",Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0342,12.0,85167358.0,86764676.0,1597318.0,315394.0,315547.0,SNP_A-2082757,SNP_A-4221284,154.0,...,"KISUMU, Kenya",Kenya,1951.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,ML2229,12.0,42771930.0,44287191.0,1515261.0,308987.0,309181.0,SNP_A-2055076,SNP_A-1848784,195.0,...,"NYAMIRA, Kenya",Kenya,?,unknown,unknown,"Bantus, all included","Bantus, all included","Kenyan, all included","Kenyan, all included","Kenyan, all included"
80,ML2229,12.0,110208122.0,111719705.0,1511583.0,319634.0,319775.0,SNP_A-4291625,SNP_A-1787547,142.0,...,"NYAMIRA, Kenya",Kenya,?,unknown,unknown,"Bantus, all included","Bantus, all included","Kenyan, all included","Kenyan, all included","Kenyan, all included"
81,ML2254,12.0,57850064.0,59696984.0,1846920.0,311131.0,311368.0,SNP_A-2064327,SNP_A-1792751,238.0,...,"Muleba, Tanzania",Tanzania,1965.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
82,ML2272,12.0,86044095.0,87986976.0,1942881.0,315464.0,315701.0,SNP_A-2258874,SNP_A-1788745,238.0,...,"Thika, Kenya",Kenya,1978.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
83,ML2287,12.0,50891430.0,53629895.0,2738465.0,310031.0,310530.0,SNP_A-2267881,SNP_A-2155618,500.0,...,"MURANG'A, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0141,13.0,86566879.0,88901047.0,2334168.0,335279.0,335561.0,SNP_A-4228331,SNP_A-1838334,283.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0157,13.0,36009261.0,38727413.0,2718152.0,327036.0,327587.0,SNP_A-1836723,SNP_A-2083268,552.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0313,13.0,52582043.0,54545894.0,1963851.0,329903.0,330189.0,SNP_A-2219996,SNP_A-1847511,287.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0315,13.0,76095994.0,77916928.0,1820934.0,333593.0,333930.0,SNP_A-2226160,SNP_A-2162351,338.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0612,13.0,40667660.0,42213138.0,1545478.0,327942.0,328207.0,SNP_A-2057280,SNP_A-1960261,266.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0623,13.0,66470851.0,68118604.0,1647753.0,331881.0,332090.0,SNP_A-1799111,SNP_A-1831166,210.0,...,Tanzania,Tanzania,1943.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0657,13.0,57006356.0,58825108.0,1818752.0,330466.0,330749.0,SNP_A-1838921,SNP_A-4237503,284.0,...,Tanzania,Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML0684,13.0,76463973.0,78234742.0,1770769.0,333682.0,333984.0,SNP_A-2224615,SNP_A-1830270,303.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML0752,13.0,60315288.0,63186949.0,2871661.0,331004.0,331373.0,SNP_A-1820471,SNP_A-2147546,370.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML0752,13.0,63201537.0,65114380.0,1912843.0,331375.0,331632.0,SNP_A-2220242,SNP_A-2023596,258.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML0858,13.0,94921466.0,96437415.0,1515949.0,336722.0,336890.0,SNP_A-2314939,SNP_A-2176670,169.0,...,"CHAHAFI, Uganda",Uganda,1957.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
11,ML0875,13.0,57133204.0,60089523.0,2956319.0,330478.0,330938.0,SNP_A-1949293,SNP_A-4253360,461.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
12,ML0960,13.0,80491749.0,82185787.0,1694038.0,334376.0,334602.0,SNP_A-2118928,SNP_A-1925768,227.0,...,"Nyeri, Kenya",Kenya,1952.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
13,ML1008,13.0,67094848.0,68665964.0,1571116.0,331978.0,332182.0,SNP_A-2142565,SNP_A-2086284,205.0,...,"Bukoba, Tanzania",Tanzania,1966.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML1072,13.0,30142180.0,31754197.0,1612017.0,325868.0,326235.0,SNP_A-2061971,SNP_A-2122251,368.0,...,"Nyeri, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
15,ML1151,13.0,60363721.0,65392365.0,5028644.0,331028.0,331684.0,SNP_A-4226826,SNP_A-4285666,657.0,...,"Mbale, Uganda",Uganda,1961.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
16,ML1160,13.0,108927210.0,110581455.0,1654245.0,339583.0,339951.0,SNP_A-2103710,SNP_A-1878737,369.0,...,Tanzania,Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
17,ML1203,13.0,23625901.0,25391476.0,1765575.0,324490.0,324845.0,SNP_A-2114732,SNP_A-2179475,356.0,...,"Machakos, Kenya",Kenya,1956.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
18,ML1208,13.0,36215865.0,38008533.0,1792668.0,327073.0,327427.0,SNP_A-1794090,SNP_A-1811111,355.0,...,"Bukoba, Tanzania",Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
19,ML1233,13.0,84106883.0,85860890.0,1754007.0,334870.0,335175.0,SNP_A-1940814,SNP_A-4301215,306.0,...,"Embu, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
20,ML1286,13.0,66711848.0,68285656.0,1573808.0,331914.0,332110.0,SNP_A-2070338,SNP_A-2199999,197.0,...,"Kiambu, Kenya",Kenya,1951.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
21,ML1293,13.0,87174600.0,88980864.0,1806264.0,335328.0,335572.0,SNP_A-2169141,SNP_A-2092010,245.0,...,Kenya,Kenya,1954.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
22,ML1308,13.0,39716653.0,41408305.0,1691652.0,327787.0,328043.0,SNP_A-4241732,SNP_A-2172177,257.0,...,Tanzania,Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
23,ML1315,13.0,40659565.0,42355890.0,1696325.0,327941.0,328233.0,SNP_A-4279835,SNP_A-1836447,293.0,...,"Bukoba, Tanzania",Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
24,ML1450,13.0,85184976.0,87179035.0,1994059.0,335063.0,335329.0,SNP_A-4282850,SNP_A-4293791,267.0,...,"NYAHURURU, Kenya",Kenya,1972.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML1497,13.0,54004691.0,56035097.0,2030406.0,330119.0,330389.0,SNP_A-4282654,SNP_A-1956848,271.0,...,"KAGERA, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
26,ML1497,13.0,56805841.0,58676036.0,1870195.0,330443.0,330693.0,SNP_A-2096528,SNP_A-4284916,251.0,...,"KAGERA, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
27,ML1497,13.0,88777265.0,90562593.0,1785328.0,335551.0,335837.0,SNP_A-2288456,SNP_A-2023959,287.0,...,"KAGERA, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
28,ML1687,13.0,54210712.0,56035097.0,1824385.0,330152.0,330389.0,SNP_A-2139671,SNP_A-1956848,238.0,...,"MURANG'A, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
29,ML1773,13.0,81194977.0,83248205.0,2053228.0,334467.0,334760.0,SNP_A-2164509,SNP_A-4228833,294.0,...,"MURANG'A, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
30,ML1773,13.0,83267045.0,88682441.0,5415396.0,334762.0,335537.0,SNP_A-1815975,SNP_A-2170392,776.0,...,"MURANG'A, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
31,ML1782,13.0,42644081.0,45391813.0,2747732.0,328287.0,328821.0,SNP_A-2233146,SNP_A-2195870,535.0,...,"Machakos, Kenya",Kenya,1959.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
32,ML1810,13.0,54041427.0,56035097.0,1993670.0,330124.0,330389.0,SNP_A-4223151,SNP_A-1956848,266.0,...,"Nyeri, Kenya",Kenya,1974.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
33,ML1810,13.0,56805841.0,58825108.0,2019267.0,330443.0,330749.0,SNP_A-2096528,SNP_A-4237503,307.0,...,"Nyeri, Kenya",Kenya,1974.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
34,ML1871,13.0,82451568.0,84006916.0,1555348.0,334639.0,334853.0,SNP_A-2076562,SNP_A-2166765,215.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
35,ML1907,13.0,63979805.0,66737022.0,2757217.0,331512.0,331919.0,SNP_A-2072404,SNP_A-1937177,408.0,...,"Nakuru, Kenya",Kenya,1971.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
36,ML1917,13.0,97654654.0,99515767.0,1861113.0,337110.0,337449.0,SNP_A-2279639,SNP_A-2114372,340.0,...,"Machakos, Kenya",Kenya,1970.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
37,ML1943,13.0,85184976.0,87294807.0,2109831.0,335063.0,335344.0,SNP_A-4282850,SNP_A-2262009,282.0,...,"NYANDARUA, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
38,ML1956,13.0,80563480.0,83411057.0,2847577.0,334382.0,334778.0,SNP_A-2091348,SNP_A-4228854,397.0,...,"Nyeri, Kenya",Kenya,1964.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
39,ML2029,13.0,23515032.0,25248861.0,1733829.0,324442.0,324822.0,SNP_A-2025225,SNP_A-4281927,381.0,...,"Bukoba, Tanzania",Tanzania,1975.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
40,ML2069,13.0,61842042.0,63353166.0,1511124.0,331219.0,331389.0,SNP_A-2308771,SNP_A-2147710,171.0,...,"Kakamega, Kenya",Kenya,1959.0,"Abaluhya, Kenya, close to Bantus","Abaluhya, Kenya, close to Bantus","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
41,ML2126,13.0,78759623.0,80630353.0,1870730.0,334095.0,334388.0,SNP_A-2003418,SNP_A-4196295,294.0,...,"Meru, Kenya",Kenya,1978.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
42,ML2158,13.0,83220374.0,84765128.0,1544754.0,334756.0,335004.0,SNP_A-2128712,SNP_A-4228986,249.0,...,"Nyeri, Kenya",Kenya,1971.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
43,ML2203,13.0,57133204.0,58652136.0,1518932.0,330478.0,330689.0,SNP_A-1949293,SNP_A-2243393,212.0,...,"Thika, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
44,ML2229,13.0,93386359.0,94975000.0,1588641.0,336393.0,336733.0,SNP_A-2129772,SNP_A-1894667,341.0,...,"NYAMIRA, Kenya",Kenya,?,unknown,unknown,"Bantus, all included","Bantus, all included","Kenyan, all included","Kenyan, all included","Kenyan, all included"
45,ML2263,13.0,70295288.0,74033881.0,3738593.0,332466.0,333166.0,SNP_A-2226883,SNP_A-2064154,701.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
46,ML2263,13.0,74101304.0,76076813.0,1975509.0,333177.0,333591.0,SNP_A-2207570,SNP_A-2281102,415.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
47,ML2263,13.0,76095994.0,79441371.0,3345377.0,333593.0,334194.0,SNP_A-2226160,SNP_A-2049823,602.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
48,ML2263,13.0,80792048.0,89050001.0,8257953.0,334412.0,335577.0,SNP_A-2312087,SNP_A-2168441,1166.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
49,ML2263,13.0,89057063.0,92220335.0,3163272.0,335579.0,336144.0,SNP_A-2246504,SNP_A-4240832,566.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
50,ML2263,13.0,92223689.0,96645443.0,4421754.0,336146.0,336930.0,SNP_A-1952462,SNP_A-2123403,785.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
51,ML2263,13.0,98919672.0,100530564.0,1610892.0,337365.0,337622.0,SNP_A-4251470,SNP_A-2244222,258.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
52,ML2263,13.0,100960081.0,105961871.0,5001790.0,337725.0,338905.0,SNP_A-2216231,SNP_A-2185610,1181.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
53,ML2271,13.0,62104068.0,64262071.0,2158003.0,331241.0,331554.0,SNP_A-4224097,SNP_A-2110931,314.0,...,"MURANG'A, Kenya",Kenya,1975.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
54,ML2271,13.0,85245812.0,86831667.0,1585855.0,335091.0,335295.0,SNP_A-2284426,SNP_A-2203285,205.0,...,"MURANG'A, Kenya",Kenya,1975.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
55,ML2285,13.0,65117432.0,68358130.0,3240698.0,331636.0,332125.0,SNP_A-4201623,SNP_A-4280572,490.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0141,14.0,40579588.0,42276333.0,1696745.0,343760.0,343974.0,SNP_A-2065830,SNP_A-2162550,215.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0142,14.0,34035039.0,38581192.0,4546153.0,342770.0,343450.0,SNP_A-1937004,SNP_A-2208463,681.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0170,14.0,34773272.0,37780249.0,3006977.0,342831.0,343340.0,SNP_A-2050447,SNP_A-1890645,510.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0190,14.0,70050177.0,71693762.0,1643585.0,348379.0,348651.0,SNP_A-4224767,SNP_A-1902245,273.0,...,"Busia, Kenya",Kenya,1963.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
4,ML0256,14.0,65511300.0,67779821.0,2268521.0,347654.0,347944.0,SNP_A-1900484,SNP_A-1820020,291.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0603,14.0,26553240.0,28092616.0,1539376.0,341637.0,341832.0,SNP_A-1793076,SNP_A-2199907,196.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0703,14.0,86809667.0,88682720.0,1873053.0,351217.0,351500.0,SNP_A-4227644,SNP_A-2244867,284.0,...,"Bukoba, Tanzania",Tanzania,1953.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML1000,14.0,101876044.0,103732081.0,1856037.0,353952.0,354126.0,SNP_A-4230098,SNP_A-2070868,175.0,...,"Bukoba, Tanzania",Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML1025,14.0,73735385.0,76129425.0,2394040.0,349022.0,349367.0,SNP_A-1891464,SNP_A-1789649,346.0,...,"NAKASEKE, Uganda",Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML1030,14.0,27945491.0,29674514.0,1729023.0,341814.0,342001.0,SNP_A-2246397,SNP_A-1813836,188.0,...,"Bukoba, Tanzania",Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML1042,14.0,23463409.0,25061301.0,1597892.0,341134.0,341409.0,SNP_A-2061692,SNP_A-4235644,276.0,...,Tanzania,Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
11,ML1051,14.0,78097257.0,81012682.0,2915425.0,349773.0,350231.0,SNP_A-4232966,SNP_A-1803320,459.0,...,"Kiambu, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
12,ML1068,14.0,29114999.0,31478668.0,2363669.0,341938.0,342221.0,SNP_A-4226296,SNP_A-4294217,284.0,...,Tanzania,Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
13,ML1144,14.0,96927485.0,100542473.0,3614988.0,353026.0,353803.0,SNP_A-4236106,SNP_A-4302507,778.0,...,Uganda,Uganda,1974.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML1203,14.0,63447661.0,65404894.0,1957233.0,347338.0,347631.0,SNP_A-2302546,SNP_A-1854974,294.0,...,"Machakos, Kenya",Kenya,1956.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
15,ML1286,14.0,71624206.0,73363284.0,1739078.0,348634.0,348947.0,SNP_A-1799710,SNP_A-2242745,314.0,...,"Kiambu, Kenya",Kenya,1951.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
16,ML1316,14.0,39416940.0,41334938.0,1917998.0,343547.0,343855.0,SNP_A-1923205,SNP_A-4203588,309.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
17,ML1362,14.0,102002832.0,104308725.0,2305893.0,353963.0,354159.0,SNP_A-4282842,SNP_A-2232252,197.0,...,"Embu, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
18,ML1387,14.0,33048257.0,36039213.0,2990956.0,342568.0,343022.0,SNP_A-1933638,SNP_A-2227677,455.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
19,ML1387,14.0,37705495.0,39309123.0,1603628.0,343322.0,343535.0,SNP_A-4246131,SNP_A-1944904,214.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
20,ML1387,14.0,40392744.0,42934100.0,2541356.0,343717.0,344066.0,SNP_A-1948821,SNP_A-2211041,350.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
21,ML1387,14.0,45176961.0,48943638.0,3766677.0,344288.0,344846.0,SNP_A-2219539,SNP_A-2097131,559.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
22,ML1391,14.0,53744110.0,56049697.0,2305587.0,345680.0,346145.0,SNP_A-2114287,SNP_A-2229232,466.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
23,ML1416,14.0,66262776.0,68371458.0,2108682.0,347766.0,348087.0,SNP_A-2146766,SNP_A-2024992,322.0,...,"MURANG'A, Kenya",Kenya,1944.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
24,ML1416,14.0,70379350.0,71884406.0,1505056.0,348436.0,348717.0,SNP_A-1795772,SNP_A-2254046,282.0,...,"MURANG'A, Kenya",Kenya,1944.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML1430,14.0,38811715.0,42297072.0,3485357.0,343475.0,343975.0,SNP_A-4279770,SNP_A-4232713,501.0,...,"Kitui, Kenya",Kenya,1967.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
26,ML1441,14.0,82186231.0,83974102.0,1787871.0,350405.0,350734.0,SNP_A-1820628,SNP_A-2003895,330.0,...,"Nairobi, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
27,ML1482,14.0,90184248.0,92073693.0,1889445.0,351756.0,352073.0,SNP_A-2245720,SNP_A-2306494,318.0,...,"MURANG'A, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
28,ML1529,14.0,41762206.0,44706257.0,2944051.0,343912.0,344262.0,SNP_A-2210535,SNP_A-2193995,351.0,...,"Siaya, Kenya",Kenya,1963.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
29,ML1535,14.0,93223168.0,95013301.0,1790133.0,352220.0,352615.0,SNP_A-2303536,SNP_A-4273584,396.0,...,"Makueni, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
30,ML1609,14.0,100661581.0,103610922.0,2949341.0,353828.0,354122.0,SNP_A-1874817,SNP_A-1875718,295.0,...,"Nyeri, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
31,ML1665,14.0,32106408.0,34333734.0,2227326.0,342335.0,342793.0,SNP_A-2198431,SNP_A-2044370,459.0,...,"SAGANA, Kenya",Kenya,1973.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
32,ML1667,14.0,70685110.0,72276082.0,1590972.0,348482.0,348802.0,SNP_A-4206246,SNP_A-2279501,321.0,...,"Kisii, Kenya",Kenya,1961.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
33,ML1706,14.0,52898072.0,54649266.0,1751194.0,345508.0,345838.0,SNP_A-4299834,SNP_A-2218864,331.0,...,"Machakos, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
34,ML1725,14.0,92026769.0,93578299.0,1551530.0,352063.0,352300.0,SNP_A-2123016,SNP_A-2105674,238.0,...,"Laikipia, Kenya",Kenya,1966.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
35,ML1766,14.0,37705485.0,41312007.0,3606522.0,343321.0,343853.0,SNP_A-4296098,SNP_A-1881158,533.0,...,"Kitui, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
36,ML1803,14.0,65486022.0,66982545.0,1496523.0,347645.0,347820.0,SNP_A-2226441,SNP_A-1794783,176.0,...,"Laikipia, Kenya",Kenya,1955.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
37,ML1810,14.0,37341401.0,42258456.0,4917055.0,343277.0,343969.0,SNP_A-1869204,SNP_A-2279261,693.0,...,"Nyeri, Kenya",Kenya,1974.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
38,ML1845,14.0,80072016.0,82968974.0,2896958.0,350106.0,350557.0,SNP_A-2236745,SNP_A-1939247,452.0,...,"Bukoba, Tanzania",Tanzania,?,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
39,ML1899,14.0,72455419.0,74756611.0,2301192.0,348848.0,349154.0,SNP_A-1854666,SNP_A-2081607,307.0,...,"MURANG'A, Kenya",Kenya,1973.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
40,ML2028,14.0,32606647.0,36156712.0,3550065.0,342433.0,343047.0,SNP_A-2099711,SNP_A-1812904,615.0,...,"Bukoba, Tanzania",Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
41,ML2028,14.0,36159682.0,38075200.0,1915518.0,343049.0,343389.0,SNP_A-2039397,SNP_A-2208142,341.0,...,"Bukoba, Tanzania",Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
42,ML2142,14.0,61442173.0,64110433.0,2668260.0,347034.0,347429.0,SNP_A-1872473,SNP_A-2163663,396.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
43,ML2142,14.0,64117025.0,67116492.0,2999467.0,347431.0,347850.0,SNP_A-4293450,SNP_A-1792986,420.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
44,ML2218,14.0,58661754.0,60535613.0,1873859.0,346609.0,346869.0,SNP_A-2100013,SNP_A-2087708,261.0,...,"Kiambu, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
45,ML2263,14.0,55928266.0,57515822.0,1587556.0,346116.0,346418.0,SNP_A-2220130,SNP_A-2044706,303.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
46,ML2264,14.0,26571709.0,28338910.0,1767201.0,341641.0,341871.0,SNP_A-2071967,SNP_A-2286916,231.0,...,"Thika, Kenya",Kenya,1974.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
47,ML2267,14.0,27501152.0,29054049.0,1552897.0,341764.0,341933.0,SNP_A-2133721,SNP_A-1854335,170.0,...,"MURANG'A, Kenya",Kenya,1978.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0002,15.0,34347151.0,35979748.0,1632597.0,356214.0,356501.0,SNP_A-2270123,SNP_A-1816205,288.0,...,Tanzania,Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0412,15.0,73771150.0,75610586.0,1839436.0,362412.0,362595.0,SNP_A-4302858,SNP_A-1938724,184.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0589,15.0,66415690.0,68821067.0,2405377.0,361470.0,361882.0,SNP_A-2293368,SNP_A-4237459,413.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0589,15.0,68853393.0,70530512.0,1677119.0,361890.0,362118.0,SNP_A-4197867,SNP_A-2117373,229.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0623,15.0,62570778.0,64707615.0,2136837.0,360931.0,361162.0,SNP_A-2291605,SNP_A-1794317,232.0,...,Tanzania,Tanzania,1943.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0630,15.0,40156840.0,41721187.0,1564347.0,357138.0,357295.0,SNP_A-2164268,SNP_A-2275229,158.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0713,15.0,48131276.0,50010681.0,1879405.0,358237.0,358523.0,SNP_A-2145196,SNP_A-2004157,287.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML0790,15.0,53793024.0,55387780.0,1594756.0,359268.0,359460.0,SNP_A-2284152,SNP_A-4295449,193.0,...,"CHAHAFI, Uganda",Uganda,1959.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML0790,15.0,55390661.0,57254613.0,1863952.0,359462.0,359879.0,SNP_A-2226675,SNP_A-1947427,418.0,...,"CHAHAFI, Uganda",Uganda,1959.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML0858,15.0,74264093.0,76127594.0,1863501.0,362461.0,362666.0,SNP_A-2213340,SNP_A-4300380,206.0,...,"CHAHAFI, Uganda",Uganda,1957.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML0887,15.0,57165586.0,58819346.0,1653760.0,359866.0,360159.0,SNP_A-2287230,SNP_A-2277603,294.0,...,"MURANG'A, Kenya",Kenya,1952.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
11,ML1138,15.0,36124633.0,38077319.0,1952686.0,356517.0,356933.0,SNP_A-2179790,SNP_A-2273215,417.0,...,"Nairobi, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
12,ML1151,15.0,91523799.0,95773264.0,4249465.0,365264.0,366110.0,SNP_A-2073528,SNP_A-2092978,847.0,...,"Mbale, Uganda",Uganda,1961.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
13,ML1337,15.0,40100184.0,41721187.0,1621003.0,357122.0,357295.0,SNP_A-2274357,SNP_A-2275229,174.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML1489,15.0,21729952.0,23564392.0,1834440.0,354383.0,354610.0,SNP_A-2135097,SNP_A-1897872,228.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
15,ML1530,15.0,84712317.0,87948591.0,3236274.0,363935.0,364628.0,SNP_A-2128354,SNP_A-2265205,694.0,...,"Kakamega, Kenya",Kenya,1963.0,"Abaluhya, Kenya, close to Bantus","Abaluhya, Kenya, close to Bantus","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
16,ML1548,15.0,31050093.0,32564059.0,1513966.0,355550.0,355903.0,SNP_A-1950328,SNP_A-4299546,354.0,...,"Kitui, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
17,ML1548,15.0,32972895.0,36790701.0,3817806.0,356002.0,356636.0,SNP_A-1931776,SNP_A-1859554,635.0,...,"Kitui, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
18,ML1625,15.0,40156840.0,41721187.0,1564347.0,357138.0,357295.0,SNP_A-2164268,SNP_A-2275229,158.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
19,ML1695,15.0,40210748.0,41721187.0,1510439.0,357148.0,357295.0,SNP_A-1933480,SNP_A-2275229,148.0,...,"Bukoba, Tanzania",Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
20,ML1705,15.0,38509718.0,40077489.0,1567771.0,356982.0,357117.0,SNP_A-1800237,SNP_A-2240556,136.0,...,"Bukoba, Tanzania",Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
21,ML1776,15.0,37907672.0,39939782.0,2032110.0,356901.0,357098.0,SNP_A-2202623,SNP_A-2058703,198.0,...,"Bukoba, Tanzania",Tanzania,1975.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
22,ML1796,15.0,40205377.0,41721187.0,1515810.0,357147.0,357295.0,SNP_A-4226874,SNP_A-2275229,149.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
23,ML1814,15.0,37907672.0,40094970.0,2187298.0,356901.0,357120.0,SNP_A-2202623,SNP_A-2274351,220.0,...,"MURANG'A, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
24,ML1828,15.0,34647876.0,36616462.0,1968586.0,356259.0,356598.0,SNP_A-2270387,SNP_A-2022634,340.0,...,Kenya,Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML1833,15.0,39992243.0,41721187.0,1728944.0,357105.0,357295.0,SNP_A-2059243,SNP_A-2275229,191.0,...,"Machakos, Kenya",Kenya,1961.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
26,ML1904,15.0,57934765.0,59960277.0,2025512.0,360011.0,360487.0,SNP_A-4218174,SNP_A-4197300,477.0,...,"KIRINYAGA, Kenya",Kenya,1967.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
27,ML2037,15.0,47008131.0,51801197.0,4793066.0,358092.0,358907.0,SNP_A-4300746,SNP_A-4228757,816.0,...,"Bukoba, Tanzania",Tanzania,1969.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
28,ML2128,15.0,77159468.0,78899775.0,1740307.0,362823.0,363212.0,SNP_A-2118818,SNP_A-2241212,390.0,...,"Kakamega, Kenya",Kenya,1966.0,"Abaluhya, Kenya, close to Bantus","Abaluhya, Kenya, close to Bantus","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
29,ML2142,15.0,88593510.0,93616492.0,5022982.0,364699.0,365747.0,SNP_A-4255052,SNP_A-1812479,1049.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
30,ML2142,15.0,97343311.0,100192115.0,2848804.0,366361.0,366842.0,SNP_A-2138073,SNP_A-1843077,482.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
31,ML2196,15.0,40210748.0,41721187.0,1510439.0,357148.0,357295.0,SNP_A-1933480,SNP_A-2275229,148.0,...,"Nyeri, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
32,ML2263,15.0,87280374.0,90512095.0,3231721.0,364514.0,365047.0,SNP_A-2149732,SNP_A-1856595,534.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
33,ML2263,15.0,90514134.0,92458377.0,1944243.0,365049.0,365504.0,SNP_A-2284277,SNP_A-1871837,456.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0002,16.0,45122807.0,46719572.0,1596765.0,371953.0,372055.0,SNP_A-4205291,SNP_A-2022078,103.0,...,Tanzania,Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0142,16.0,46935402.0,48478825.0,1543423.0,372086.0,372345.0,SNP_A-4200849,SNP_A-4301592,260.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0313,16.0,69184729.0,70815200.0,1630471.0,375653.0,375835.0,SNP_A-2230301,SNP_A-2256703,183.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0589,16.0,56479057.0,58392927.0,1913870.0,373884.0,374183.0,SNP_A-2254497,SNP_A-2149738,300.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0589,16.0,66369431.0,68681849.0,2312418.0,375371.0,375627.0,SNP_A-1960491,SNP_A-2195311,257.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0703,16.0,69944391.0,71553663.0,1609272.0,375729.0,375929.0,SNP_A-1903711,SNP_A-2201530,201.0,...,"Bukoba, Tanzania",Tanzania,1953.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0825,16.0,48860061.0,52120096.0,3260035.0,372374.0,373032.0,SNP_A-4294855,SNP_A-4243954,659.0,...,"CHAHAFI, Uganda",Uganda,1955.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML0874,16.0,70603712.0,72906544.0,2302832.0,375811.0,376171.0,SNP_A-4272041,SNP_A-2155926,361.0,...,"Makueni, Kenya",Kenya,1947.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
8,ML0926,16.0,45122807.0,47298209.0,2175402.0,371953.0,372126.0,SNP_A-4205291,SNP_A-2256884,174.0,...,"CHAHAFI, Uganda",Uganda,1967.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML0946,16.0,62024148.0,64782081.0,2757933.0,374684.0,375237.0,SNP_A-2225036,SNP_A-4245896,554.0,...,"Bukoba, Tanzania",Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML1030,16.0,45891124.0,47449122.0,1557998.0,371993.0,372158.0,SNP_A-1854850,SNP_A-1807282,166.0,...,"Bukoba, Tanzania",Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
11,ML1054,16.0,69998220.0,71754160.0,1755940.0,375739.0,375948.0,SNP_A-2060644,SNP_A-1827048,210.0,...,"Bukoba, Tanzania",Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
12,ML1307,16.0,53780708.0,55577828.0,1797120.0,373378.0,373760.0,SNP_A-2004728,SNP_A-2220604,383.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
13,ML1308,16.0,45295011.0,47739397.0,2444386.0,371964.0,372217.0,SNP_A-2004675,SNP_A-2242458,254.0,...,Tanzania,Tanzania,1968.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML1418,16.0,69567857.0,71835090.0,2267233.0,375690.0,375951.0,SNP_A-2213177,SNP_A-1860331,262.0,...,"JINJA, Uganda",Uganda,1966.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
15,ML1490,16.0,48860061.0,53440164.0,4580103.0,372374.0,373318.0,SNP_A-4294855,SNP_A-1864084,945.0,...,"Machakos, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
16,ML1535,16.0,45226833.0,47086325.0,1859492.0,371960.0,372100.0,SNP_A-1827680,SNP_A-1955480,141.0,...,"Makueni, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
17,ML1597,16.0,24281404.0,26000586.0,1719182.0,371022.0,371303.0,SNP_A-2286207,SNP_A-4294378,282.0,...,"MURANG'A, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
18,ML1616,16.0,24281404.0,26000586.0,1719182.0,371022.0,371303.0,SNP_A-2286207,SNP_A-4294378,282.0,...,"MURANG'A, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
19,ML1695,16.0,73510641.0,75123418.0,1612777.0,376264.0,376546.0,SNP_A-4260657,SNP_A-2004871,283.0,...,"Bukoba, Tanzania",Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
20,ML1705,16.0,69606282.0,71485034.0,1878752.0,375692.0,375919.0,SNP_A-2027914,SNP_A-1815770,228.0,...,"Bukoba, Tanzania",Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
21,ML1747,16.0,45199957.0,46731833.0,1531876.0,371957.0,372060.0,SNP_A-4284380,SNP_A-2275966,104.0,...,"MARAGWA, Kenya",Kenya,1952.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
22,ML1748,16.0,45891124.0,48078375.0,2187251.0,371993.0,372282.0,SNP_A-1854850,SNP_A-2118880,290.0,...,"Machakos, Kenya",Kenya,1954.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
23,ML1828,16.0,45199957.0,47094922.0,1894965.0,371957.0,372103.0,SNP_A-4284380,SNP_A-1798258,147.0,...,Kenya,Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
24,ML1923,16.0,56479057.0,59000229.0,2521172.0,373884.0,374258.0,SNP_A-2254497,SNP_A-1807124,375.0,...,"Machakos, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML1928,16.0,63978174.0,65530882.0,1552708.0,375045.0,375340.0,SNP_A-4204982,SNP_A-2198834,296.0,...,"Bukoba, Tanzania",Tanzania,1966.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
26,ML2019,16.0,70064484.0,71754160.0,1689676.0,375751.0,375948.0,SNP_A-1848436,SNP_A-1827048,198.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
27,ML2113,16.0,45559127.0,47071325.0,1512198.0,371978.0,372097.0,SNP_A-1828684,SNP_A-1952790,120.0,...,"MURANG'A, Kenya",Kenya,1973.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
28,ML2135,16.0,45340861.0,47017059.0,1676198.0,371967.0,372092.0,SNP_A-2103518,SNP_A-2166518,126.0,...,"Kiambu, Kenya",Kenya,1967.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
29,ML2261,16.0,45340861.0,47115419.0,1774558.0,371967.0,372105.0,SNP_A-2103518,SNP_A-2195895,139.0,...,"Machakos, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0030,17.0,53966870.0,55698601.0,1731731.0,387031.0,387134.0,SNP_A-1864767,SNP_A-1815963,104.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0608,17.0,53327308.0,55565566.0,2238258.0,386975.0,387129.0,SNP_A-4223473,SNP_A-1796579,155.0,...,"CHAHAFI, Uganda",Uganda,1956.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0646,17.0,70122718.0,71958946.0,1836228.0,389152.0,389317.0,SNP_A-2186281,SNP_A-2209242,166.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0888,17.0,13618099.0,15508394.0,1890295.0,382210.0,382575.0,SNP_A-1882277,SNP_A-1880207,366.0,...,"MURANG'A, Kenya",Kenya,1959.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
4,ML0888,17.0,16806979.0,18308015.0,1501036.0,382652.0,382803.0,SNP_A-2090542,SNP_A-1877022,152.0,...,"MURANG'A, Kenya",Kenya,1959.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
5,ML0959,17.0,47241700.0,52230102.0,4988402.0,385833.0,386755.0,SNP_A-1859039,SNP_A-2114881,923.0,...,"MURANG'A, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
6,ML1332,17.0,48824655.0,50347267.0,1522612.0,386112.0,386337.0,SNP_A-4199201,SNP_A-1921923,226.0,...,Tanzania,Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML1481,17.0,57990558.0,59781521.0,1790963.0,387300.0,387463.0,SNP_A-2303675,SNP_A-1856272,164.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
8,ML1497,17.0,70348607.0,72424804.0,2076197.0,389180.0,389376.0,SNP_A-1805422,SNP_A-2059149,197.0,...,"KAGERA, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML1554,17.0,47151791.0,50272579.0,3120788.0,385810.0,386301.0,SNP_A-2005190,SNP_A-2272947,492.0,...,"MURANG'A, Kenya",Kenya,1955.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
10,ML1591,17.0,48362435.0,49915338.0,1552903.0,386054.0,386237.0,SNP_A-4302927,SNP_A-2204435,184.0,...,"Meru, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
11,ML1781,17.0,48382259.0,50224657.0,1842398.0,386058.0,386290.0,SNP_A-2143466,SNP_A-1927158,233.0,...,"Bukoba, Tanzania",Tanzania,1974.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
12,ML1807,17.0,12606739.0,14240617.0,1633878.0,382013.0,382319.0,SNP_A-4295680,SNP_A-1941869,307.0,...,"Thika, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
13,ML1817,17.0,6193608.0,7955033.0,1761425.0,380974.0,381181.0,SNP_A-1818467,SNP_A-2182736,208.0,...,"Bukoba, Tanzania",Tanzania,1970.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML2042,17.0,36149026.0,37990643.0,1841617.0,384587.0,384854.0,SNP_A-4249588,SNP_A-2148906,268.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
15,ML2287,17.0,36264388.0,37990643.0,1726255.0,384608.0,384854.0,SNP_A-2156275,SNP_A-2148906,247.0,...,"MURANG'A, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
16,ML2287,17.0,38929256.0,40668583.0,1739327.0,384905.0,385074.0,SNP_A-2276933,SNP_A-4199404,170.0,...,"MURANG'A, Kenya",Kenya,?,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0041,18.0,48040400.0,52114905.0,4074505.0,397834.0,398581.0,SNP_A-1840431,SNP_A-1904877,748.0,...,Uganda,Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0058,18.0,12000646.0,13616101.0,1615455.0,392365.0,392575.0,SNP_A-2181957,SNP_A-2228985,211.0,...,"Bukoba, Tanzania",Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0260,18.0,42396267.0,44119931.0,1723664.0,396804.0,397088.0,SNP_A-1907715,SNP_A-1940819,285.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0313,18.0,19281112.0,21045556.0,1764444.0,392975.0,393303.0,SNP_A-2220675,SNP_A-2294834,329.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0320,18.0,47994772.0,50527233.0,2532461.0,397826.0,398318.0,SNP_A-2244182,SNP_A-2248170,493.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0406,18.0,42587877.0,44151658.0,1563781.0,396849.0,397099.0,SNP_A-1783236,SNP_A-4203176,251.0,...,Tanzania,Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0431,18.0,46164068.0,47955451.0,1791383.0,397466.0,397822.0,SNP_A-2138880,SNP_A-2050141,357.0,...,"Bukoba, Tanzania",Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML0431,18.0,49999395.0,51779297.0,1779902.0,398241.0,398509.0,SNP_A-1873733,SNP_A-1916039,269.0,...,"Bukoba, Tanzania",Tanzania,1964.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML0589,18.0,35001777.0,37718102.0,2716325.0,395508.0,395950.0,SNP_A-2047263,SNP_A-4244889,443.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML0825,18.0,44473215.0,46448639.0,1975424.0,397159.0,397548.0,SNP_A-2289332,SNP_A-2071102,390.0,...,"CHAHAFI, Uganda",Uganda,1955.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML0900,18.0,59948650.0,61627079.0,1678429.0,400105.0,400351.0,SNP_A-2128719,SNP_A-2005748,247.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
11,ML0926,18.0,66894737.0,68635807.0,1741070.0,401298.0,401638.0,SNP_A-2068851,SNP_A-1849392,341.0,...,"CHAHAFI, Uganda",Uganda,1967.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
12,ML1067,18.0,56063765.0,57623326.0,1559561.0,399415.0,399662.0,SNP_A-1905991,SNP_A-2220582,248.0,...,"Mureba, Tanzania",Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
13,ML1128,18.0,47511608.0,49998932.0,2487324.0,397744.0,398239.0,SNP_A-2150995,SNP_A-2204515,496.0,...,Uganda,Uganda,1966.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML1128,18.0,50289677.0,57644314.0,7354637.0,398288.0,399664.0,SNP_A-1914749,SNP_A-1855299,1377.0,...,Uganda,Uganda,1966.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
15,ML1188,18.0,71055030.0,72946878.0,1891848.0,402199.0,402675.0,SNP_A-2073498,SNP_A-2163158,477.0,...,Tanzania,Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
16,ML1208,18.0,22463097.0,24997438.0,2534341.0,393520.0,393915.0,SNP_A-1788250,SNP_A-1823047,396.0,...,"Bukoba, Tanzania",Tanzania,1956.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
17,ML1370,18.0,27303016.0,30972241.0,3669225.0,394260.0,394816.0,SNP_A-1892176,SNP_A-4254705,557.0,...,"Bukoba, Tanzania",Tanzania,1944.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
18,ML1424,18.0,32352588.0,34181512.0,1828924.0,395043.0,395340.0,SNP_A-1915285,SNP_A-2166891,298.0,...,"MURANG'A, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
19,ML1424,18.0,35168361.0,37335445.0,2167084.0,395533.0,395865.0,SNP_A-2288359,SNP_A-1825106,333.0,...,"MURANG'A, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
20,ML1452,18.0,23311217.0,25527831.0,2216614.0,393667.0,393974.0,SNP_A-2005540,SNP_A-2058046,308.0,...,"Kiambu, Kenya",Kenya,1961.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
21,ML1764,18.0,63092858.0,65047254.0,1954396.0,400597.0,400980.0,SNP_A-2282998,SNP_A-1886147,384.0,...,"LIMURU, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
22,ML1780,18.0,150887.0,2177235.0,2026348.0,390017.0,390422.0,SNP_A-1916270,SNP_A-1845185,406.0,...,"Nyeri, Kenya",Kenya,1956.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
23,ML1797,18.0,58248999.0,59989437.0,1740438.0,399799.0,400115.0,SNP_A-2187946,SNP_A-4204423,317.0,...,"Mbale, Uganda",Uganda,1973.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
24,ML1851,18.0,60612151.0,62187280.0,1575129.0,400214.0,400468.0,SNP_A-1854524,SNP_A-1925208,255.0,...,"MURANG'A, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML1868,18.0,48403984.0,50527233.0,2123249.0,397929.0,398318.0,SNP_A-2272791,SNP_A-2248170,390.0,...,"Machakos, Kenya",Kenya,1967.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
26,ML1870,18.0,55700243.0,57349688.0,1649445.0,399350.0,399620.0,SNP_A-2181887,SNP_A-1823586,271.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
27,ML2033,18.0,11818228.0,14195995.0,2377767.0,392331.0,392673.0,SNP_A-1918547,SNP_A-1885732,343.0,...,"Bukoba, Tanzania",Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
28,ML2033,18.0,37713649.0,40058316.0,2344667.0,395947.0,396322.0,SNP_A-4292129,SNP_A-4231976,376.0,...,"Bukoba, Tanzania",Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
29,ML2033,18.0,49803851.0,51878500.0,2074649.0,398210.0,398531.0,SNP_A-4259202,SNP_A-2154544,322.0,...,"Bukoba, Tanzania",Tanzania,1972.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
30,ML2072,18.0,405401.0,2105383.0,1699982.0,390059.0,390396.0,SNP_A-4252220,SNP_A-4220692,338.0,...,"Machakos, Kenya",Kenya,1962.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
31,ML2122,18.0,44088554.0,45598723.0,1510169.0,397082.0,397318.0,SNP_A-1840678,SNP_A-1882959,237.0,...,"Makueni, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
32,ML2128,18.0,61842366.0,63407074.0,1564708.0,400408.0,400637.0,SNP_A-2065351,SNP_A-2005758,230.0,...,"Kakamega, Kenya",Kenya,1966.0,"Abaluhya, Kenya, close to Bantus","Abaluhya, Kenya, close to Bantus","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
33,ML2219,18.0,38438497.0,40178035.0,1739538.0,396088.0,396336.0,SNP_A-1912452,SNP_A-4202902,249.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0199,19.0,41623797.0,43637691.0,2013894.0,406458.0,406626.0,SNP_A-2150411,SNP_A-1791707,169.0,...,"BUSOGA, Uganda",Uganda,1963.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0256,19.0,51479323.0,53572212.0,2092889.0,407266.0,407453.0,SNP_A-4193184,SNP_A-2176678,188.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0589,19.0,11088602.0,13275594.0,2186992.0,403912.0,404055.0,SNP_A-1943846,SNP_A-2160450,144.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0612,19.0,9056068.0,10774354.0,1718286.0,403751.0,403891.0,SNP_A-2032266,SNP_A-2174281,141.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0755,19.0,22358984.0,24297477.0,1938493.0,404890.0,405117.0,SNP_A-1789020,SNP_A-2140927,228.0,...,"Bukoba, Tanzania",Tanzania,1952.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0790,19.0,41939078.0,43509326.0,1570248.0,406479.0,406612.0,SNP_A-2238390,SNP_A-2216295,134.0,...,"CHAHAFI, Uganda",Uganda,1959.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML1005,19.0,21901800.0,24297477.0,2395677.0,404853.0,405117.0,SNP_A-2052703,SNP_A-2140927,265.0,...,Tanzania,Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML1072,19.0,41563135.0,43671958.0,2108823.0,406455.0,406632.0,SNP_A-1797543,SNP_A-2258454,178.0,...,"Nyeri, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
8,ML1129,19.0,20335506.0,22531602.0,2196096.0,404688.0,404906.0,SNP_A-2208390,SNP_A-2080686,219.0,...,"Mbale, Uganda",Uganda,1971.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML1336,19.0,8209705.0,10179112.0,1969407.0,403666.0,403848.0,SNP_A-2157656,SNP_A-1827202,183.0,...,Tanzania,Tanzania,1963.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML1346,19.0,49539455.0,51127600.0,1588145.0,407102.0,407241.0,SNP_A-1961256,SNP_A-1812379,140.0,...,"Bukoba, Tanzania",Tanzania,1971.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
11,ML1472,19.0,39074481.0,40702499.0,1628018.0,406204.0,406415.0,SNP_A-2056172,SNP_A-2178614,212.0,...,"Kiambu, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
12,ML1484,19.0,41623797.0,43435431.0,1811634.0,406458.0,406606.0,SNP_A-2150411,SNP_A-2075569,149.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
13,ML1588,19.0,22493301.0,24297477.0,1804176.0,404900.0,405117.0,SNP_A-2300081,SNP_A-2140927,218.0,...,Kenya,Kenya,1955.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
14,ML1671,19.0,44275000.0,46174582.0,1899582.0,406683.0,406833.0,SNP_A-4300762,SNP_A-1786217,151.0,...,"Nakuru, Kenya",Kenya,1965.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
15,ML1693,19.0,22705984.0,24297477.0,1591493.0,404933.0,405117.0,SNP_A-2032521,SNP_A-2140927,185.0,...,"Embu, Kenya",Kenya,1957.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
16,ML1765,19.0,41894154.0,43944078.0,2049924.0,406475.0,406654.0,SNP_A-1786373,SNP_A-1828680,180.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
17,ML1766,19.0,41939078.0,43453003.0,1513925.0,406479.0,406609.0,SNP_A-2238390,SNP_A-2217452,131.0,...,"Kitui, Kenya",Kenya,1953.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
18,ML1791,19.0,44014877.0,47197884.0,3183007.0,406662.0,406914.0,SNP_A-2084750,SNP_A-1786218,253.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
19,ML1791,19.0,49541405.0,51127600.0,1586195.0,407104.0,407241.0,SNP_A-2278692,SNP_A-1812379,138.0,...,"Machakos, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
20,ML1844,19.0,11319739.0,13244718.0,1924979.0,403923.0,404052.0,SNP_A-1785840,SNP_A-1891137,130.0,...,"MURANG'A, Kenya",Kenya,1966.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
21,ML1938,19.0,36625384.0,38242901.0,1617517.0,405816.0,406077.0,SNP_A-1954349,SNP_A-2186021,262.0,...,"Nakuru, Kenya",Kenya,1972.0,Luo,"Nilotes, Kenya",Nilotes,"Nilotes, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
22,ML2147,19.0,21648247.0,24297477.0,2649230.0,404834.0,405117.0,SNP_A-1902759,SNP_A-2140927,284.0,...,"Machakos, Kenya",Kenya,1961.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
23,ML2249,19.0,34468249.0,36896807.0,2428558.0,405437.0,405877.0,SNP_A-2121510,SNP_A-2088347,441.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
24,ML2249,19.0,36901654.0,38881477.0,1979823.0,405879.0,406174.0,SNP_A-1870955,SNP_A-1786473,296.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
25,ML2249,19.0,39237000.0,41040430.0,1803430.0,406224.0,406438.0,SNP_A-1798700,SNP_A-4275895,215.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
26,ML2249,19.0,42861195.0,45776703.0,2915508.0,406540.0,406805.0,SNP_A-4234917,SNP_A-1935108,266.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
27,ML2249,19.0,49256241.0,51127600.0,1871359.0,407068.0,407241.0,SNP_A-1858276,SNP_A-1812379,174.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
28,ML2249,19.0,51160543.0,53572212.0,2411669.0,407243.0,407453.0,SNP_A-1961654,SNP_A-2176678,211.0,...,"Kitui, Kenya",Kenya,1960.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0142,20.0,43908380.0,45798766.0,1890386.0,416144.0,416481.0,SNP_A-4194955,SNP_A-2176207,338.0,...,"Bukoba, Tanzania",Tanzania,1960.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0264,20.0,52230088.0,53844342.0,1614254.0,417603.0,417987.0,SNP_A-2233818,SNP_A-1968759,385.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0265,20.0,36275170.0,38046942.0,1771772.0,414748.0,415078.0,SNP_A-2106590,SNP_A-2300854,331.0,...,"Bukoba, Tanzania",Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0389,20.0,50046770.0,52149491.0,2102721.0,417172.0,417573.0,SNP_A-1874452,SNP_A-4262850,402.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
4,ML0498,20.0,24062903.0,25669248.0,1606345.0,413719.0,413994.0,SNP_A-4193612,SNP_A-2024203,276.0,...,"Bukoba, Tanzania",Tanzania,1939.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0546,20.0,32202347.0,34796050.0,2593703.0,414338.0,414577.0,SNP_A-2174378,SNP_A-1913426,240.0,...,Tanzania,Tanzania,1953.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0546,20.0,44335833.0,46358016.0,2022183.0,416216.0,416611.0,SNP_A-4289801,SNP_A-1968554,396.0,...,Tanzania,Tanzania,1953.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML1125,20.0,20068077.0,21752341.0,1684264.0,412935.0,413193.0,SNP_A-2208559,SNP_A-1921320,259.0,...,"Bukoba, Tanzania",Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML1125,20.0,23041773.0,24590499.0,1548726.0,413491.0,413826.0,SNP_A-4262772,SNP_A-2202936,336.0,...,"Bukoba, Tanzania",Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML1391,20.0,57457166.0,59004029.0,1546863.0,418742.0,419094.0,SNP_A-4281598,SNP_A-1929162,353.0,...,"Bukoba, Tanzania",Tanzania,1962.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
10,ML1702,20.0,8207959.0,10033054.0,1825095.0,410165.0,410601.0,SNP_A-2021441,SNP_A-2295440,437.0,...,"RUIRU, Kenya",Kenya,1950.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
11,ML1797,20.0,10007072.0,12780570.0,2773498.0,410595.0,411232.0,SNP_A-1967713,SNP_A-1967817,638.0,...,"Mbale, Uganda",Uganda,1973.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
12,ML1804,20.0,29309964.0,31867302.0,2557338.0,414008.0,414294.0,SNP_A-1968227,SNP_A-2070480,287.0,...,"Meru, Kenya",Kenya,1970.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
13,ML1940,20.0,32377195.0,34434934.0,2057739.0,414351.0,414559.0,SNP_A-1898036,SNP_A-2058137,209.0,...,"Bukoba, Tanzania",Tanzania,1973.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
14,ML2142,20.0,10652351.0,12627999.0,1975648.0,410759.0,411193.0,SNP_A-2191073,SNP_A-1812007,435.0,...,"Machakos, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
15,ML2197,20.0,31377143.0,34034898.0,2657755.0,414254.0,414530.0,SNP_A-1948450,SNP_A-2098106,277.0,...,"Kitui, Kenya",Kenya,1969.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
16,ML2278,20.0,32344684.0,34075294.0,1730610.0,414349.0,414533.0,SNP_A-2179795,SNP_A-1968271,185.0,...,"KAGERA, Tanzania",Tanzania,1980.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0562,21.0,36406812.0,37950401.0,1543589.0,423689.0,423956.0,SNP_A-2018790,SNP_A-2019044,268.0,...,Tanzania,Tanzania,1958.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML1402,21.0,33301078.0,34825923.0,1524845.0,423089.0,423335.0,SNP_A-2018226,SNP_A-2008056,247.0,...,"Bukoba, Tanzania",Tanzania,1946.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML1402,21.0,42531295.0,44441589.0,1910294.0,425095.0,425390.0,SNP_A-1970517,SNP_A-2020416,296.0,...,"Bukoba, Tanzania",Tanzania,1946.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML1607,21.0,29807059.0,32254024.0,2446965.0,422435.0,422908.0,SNP_A-2017674,SNP_A-1970023,474.0,...,"MURANG'A, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
4,ML1607,21.0,32397945.0,37975711.0,5577766.0,422947.0,423964.0,SNP_A-4270418,SNP_A-2008079,1018.0,...,"MURANG'A, Kenya",Kenya,1965.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
5,ML1710,21.0,29876576.0,31409788.0,1533212.0,422450.0,422746.0,SNP_A-2017682,SNP_A-2017938,297.0,...,"Bukoba, Tanzania",Tanzania,1969.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML1814,21.0,33554186.0,35163799.0,1609613.0,423147.0,423407.0,SNP_A-2018276,SNP_A-1970145,261.0,...,"MURANG'A, Kenya",Kenya,1958.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
7,ML2263,21.0,42413116.0,44798069.0,2384953.0,425068.0,425424.0,SNP_A-2020099,SNP_A-4216003,357.0,...,"KANDARA, Kenya",Kenya,1982.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

,0. CHP_File,1. Chromosome Name,2. Start Position,3. End Position,4. Length (bp),5. Start Index,6. End Index,7. Start SNP,8. End SNP,9. # SNPs,...,40. home1,41. HOME,42. year_of_birth,43. Tribes_birth,44. Tribes_language,45. bantus_nilotes,46. tribes_Language2,47. tribes_Language3,48. tribes_Language4,49. tribes_Language_un_Kenyan
0,ML0030,22.0,38503844.0,40265858.0,1762014.0,429317.0,429456.0,SNP_A-1882696,SNP_A-1787961,140.0,...,"Bukoba, Tanzania",Tanzania,1955.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
1,ML0103,22.0,36300135.0,37938679.0,1638544.0,429122.0,429260.0,SNP_A-4233179,SNP_A-1928553,139.0,...,"Bukoba, Tanzania",Tanzania,1954.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
2,ML0288,22.0,36047765.0,37818339.0,1770574.0,429101.0,429247.0,SNP_A-4201068,SNP_A-4251505,147.0,...,"Bukoba, Tanzania",Tanzania,1961.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
3,ML0385,22.0,26496402.0,31044339.0,4547937.0,427452.0,427987.0,SNP_A-4295414,SNP_A-1856086,536.0,...,"Kiambu, Kenya",Kenya,1955.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
4,ML0416,22.0,26489311.0,28236701.0,1747390.0,427447.0,427647.0,SNP_A-4291904,SNP_A-2078024,201.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
5,ML0681,22.0,27784477.0,29994496.0,2210019.0,427579.0,427856.0,SNP_A-1930959,SNP_A-1811594,278.0,...,"Bukoba, Tanzania",Tanzania,1957.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
6,ML0946,22.0,39066418.0,41028744.0,1962326.0,429367.0,429541.0,SNP_A-2082492,SNP_A-1788981,175.0,...,"Bukoba, Tanzania",Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
7,ML1025,22.0,37557991.0,41017534.0,3459543.0,429234.0,429540.0,SNP_A-4263236,SNP_A-2194547,307.0,...,"NAKASEKE, Uganda",Uganda,1964.0,"Uganda, Bantus","Bantus, Uganda","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
8,ML1125,22.0,38972598.0,41460342.0,2487744.0,429361.0,429575.0,SNP_A-2073511,SNP_A-4256643,215.0,...,"Bukoba, Tanzania",Tanzania,1959.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
9,ML1371,22.0,26162624.0,27770692.0,1608068.0,427348.0,427578.0,SNP_A-2049269,SNP_A-2206557,231.0,...,"MURANG'A, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
10,ML1764,22.0,36022884.0,37829550.0,1806666.0,429098.0,429248.0,SNP_A-4288380,SNP_A-1780958,151.0,...,"LIMURU, Kenya",Kenya,1963.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
11,ML1765,22.0,38745971.0,41460342.0,2714371.0,429339.0,429575.0,SNP_A-4277021,SNP_A-4256643,237.0,...,"Bukoba, Tanzania",Tanzania,1967.0,"Tanzania, Bantus","Bantus, Tanzania","Bantus, all included","Bantus, Tanzania, Uganda, etc.","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc","Bantus, Tanzania, Uganda, etc"
12,ML1785,22.0,38995013.0,40748301.0,1753288.0,429364.0,429512.0,SNP_A-2081862,SNP_A-2205810,149.0,...,"SAGANA, Kenya",Kenya,1968.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
13,ML2015,22.0,36161557.0,42845179.0,6683622.0,429114.0,429815.0,SNP_A-2278096,SNP_A-4286137,702.0,...,"Thika, Kenya",Kenya,1968.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"
14,ML2175,22.0,38454892.0,41412770.0,2957878.0,429315.0,429568.0,SNP_A-2059035,SNP_A-2192073,254.0,...,"Kitui, Kenya",Kenya,1959.0,"Bantus, Kenya","Bantus, Kenya","Bantus, all included","Bantus, Kenya","Kenyan, all included","Kenyan, all included","Kenyan, all included"

Empty DataFrame
Columns: []
Index: []

In [23]:
start_pos_key = "2. Start Position"

for chrom, rohs in chromosome_rohs.items():
    start_positions = np.array(sorted(rohs[start_pos_key]))
    start_positions = start_positions.reshape(-1, 1)

    n_components = 4
    if len(start_positions) < n_components:
        continue
    
    gmm = GaussianMixture(n_components=n_components)
    gmm.fit(start_positions)
    fig, axs = plt.subplots(1, 1, figsize=(15,5), tight_layout=True)
    
    counts, bins, patches = axs.hist(start_positions, bins=64)
    bin_norm = colors.Normalize(0, n_components)
    for count, bin, patch in zip(counts, bins, patches):
        color = plt.cm.viridis(bin_norm(gmm.predict(np.array([[bin]]))))
        patch.set_facecolor(color)
    plt.savefig(f"chr{chrom}_histogram.svg", format="svg")
    plt.close()

    predictions = gmm.predict(start_positions)
    with open(f"roh_start_gmm_chr{chrom}.csv", "w") as file_handle:
        writer = csv.writer(file_handle)
        writer.writerow([*header, "GMM Group"])
        for index, start_pos in enumerate(rohs[start_pos_key]):
            row = []
            for col in header:
                row.append(rohs[col][index])
            row.append(predictions[index])
            writer.writerow(row)